(()=>{'use strict';
 const en=document.documentElement.lang.startsWith('en'), panel=document.querySelector('.concierge-panel'), launcher=document.querySelector('.concierge-launcher'), greeting=document.querySelector('.concierge-greeting');
 const storage={get:k=>{try{return localStorage.getItem(k)}catch{return null}},set:(k,v)=>{try{localStorage.setItem(k,v)}catch{}}};
 let chatLang=en?'en':'id';
 const words={id:{subtitle:'Asisten Wedison Bali',greeting:'Hai, saya Wedi. Ada yang bisa dibantu?',description:'Pilih kebutuhanmu. Tim Bali bisa melanjutkan lewat WhatsApp.',note:'Menu bantuan otomatis. Balasan tim tersedia melalui WhatsApp.',items:[['Harga OTR & pilihan motor','harga'],['Baterai berlangganan BAAS','baas'],['Lokasi charging Bali','supercharge'],['Jadwalkan test ride','#test-ride'],['Bantuan pemilik & garansi','garansi']]},en:{subtitle:'Wedison Bali assistant',greeting:'Hi, I’m Wedi. How can I help?',description:'Choose what you need. Our Bali team can help further on WhatsApp.',note:'Automated help menu. Team replies are available through WhatsApp.',items:[['OTR prices & motorcycles','harga'],['BAAS battery subscription','baas'],['Bali charging locations','supercharge'],['Book a test ride','#test-ride'],['Owner support & warranty','garansi']]}};
 function render(){const w=words[chatLang];for(const key of ['subtitle','greeting','description','note'])panel.querySelector('[data-assistant-'+key+']').textContent=w[key];panel.querySelectorAll('[data-chat-lang]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.chatLang===chatLang)));const opts=panel.querySelector('.concierge-options');opts.replaceChildren();w.items.forEach(([label,route])=>{const a=document.createElement('a');a.textContent=label+' ↗';a.href=(chatLang==='en'?'/en/':'/')+route+(route.startsWith('#')?'':'/');opts.append(a)});panel.querySelector('.concierge-wa').href='https://wa.me/628195693282?text='+encodeURIComponent(chatLang==='en'?'Hello Wedison Bali, I would like some advice in English.':'Halo Wedison Bali, saya ingin konsultasi motor listrik.');panel.lang=chatLang;}
 function close(){panel.hidden=true;launcher.setAttribute('aria-expanded','false');launcher.focus();}
 function open(){panel.hidden=false;greeting.hidden=true;launcher.setAttribute('aria-expanded','true');panel.querySelector('[data-close-concierge]').focus();}
 if(panel){render();document.querySelectorAll('[data-open-concierge]').forEach(b=>b.addEventListener('click',()=>panel.hidden?open():close()));panel.querySelector('[data-close-concierge]').addEventListener('click',close);panel.querySelectorAll('[data-chat-lang]').forEach(b=>b.addEventListener('click',()=>{chatLang=b.dataset.chatLang;render()}));document.querySelector('[data-dismiss-greeting]').addEventListener('click',()=>{greeting.hidden=true;try{sessionStorage.setItem('wedison-greeted','1')}catch{}});setTimeout(()=>{try{if(sessionStorage.getItem('wedison-greeted'))return;sessionStorage.setItem('wedison-greeted','1')}catch{}if(panel.hidden && !document.querySelector('dialog[open]'))greeting.hidden=false;},9000);}
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(panel&&!panel.hidden)close();document.querySelectorAll('.hub-nav[open]').forEach(d=>d.open=false);}});
 document.addEventListener('click',e=>document.querySelectorAll('.hub-nav[open]').forEach(d=>{if(!d.contains(e.target))d.open=false}));
 document.querySelectorAll('[data-current-month]').forEach(s=>s.textContent=new Intl.DateTimeFormat(en?'en-GB':'id-ID',{month:'long',year:'numeric',timeZone:'Asia/Makassar'}).format(new Date()));
 // No tracking vendor is loaded without a configured ID and explicit consent.
 const consent=document.querySelector('.marketing-consent');let pixelId='',loaded=false;
 function loadPixel(){if(loaded||!/^\d{5,25}$/.test(pixelId)||storage.get('wedison-marketing')!=='accepted')return;loaded=true;const f=window.fbq=function(){if(f.callMethod)f.callMethod.apply(f,arguments);else f.queue.push(arguments)};f.queue=[];f.loaded=true;f.version='2.0';window._fbq=f;const s=document.createElement('script');s.async=true;s.src='https://connect.facebook.net/en_US/fbevents.js';document.head.append(s);f('consent','grant');f('init',pixelId);f('track','PageView');}
 document.querySelectorAll('[data-open-consent]').forEach(b=>b.addEventListener('click',()=>{consent.hidden=false;consent.querySelector('button').focus()}));
 document.querySelectorAll('[data-consent]').forEach(b=>b.addEventListener('click',()=>{storage.set('wedison-marketing',b.dataset.consent);consent.hidden=true;if(b.dataset.consent==='accepted'){if(loaded&&window.fbq)window.fbq('consent','grant');else loadPixel()}else if(window.fbq)window.fbq('consent','revoke');document.querySelector('[data-open-consent]')?.focus()}));
 fetch('/assets/marketing.json').then(r=>r.ok?r.json():{}).then(c=>{pixelId=String(c.metaPixelId||'');if(/^\d{5,25}$/.test(pixelId)){if(!storage.get('wedison-marketing'))consent.hidden=false;loadPixel()}}).catch(()=>{});
 document.addEventListener('click',e=>{const a=e.target.closest('a');if(!a||storage.get('wedison-marketing')!=='accepted')return;const event=a.dataset.event||(a.href.startsWith('https://wa.me/')?'contact':null);if(!event)return;const payload={action:event,page:location.pathname,language:en?'en':'id'};window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:'wedison_interaction',...payload});if(loaded&&window.fbq)window.fbq('trackCustom','WedisonInteraction',payload);});
})();
